FROM clojure

RUN apt-get -yqq update
RUN apt-get -yqq install apache2 git

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid
ENV APACHE_RUN_DIR /var/run/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2

RUN mkdir -p $APACHE_RUN_DIR $APACHE_LOCK_DIR $APACHE_LOG_DIR

RUN git clone https://github.com/yogthos/Clojure-Tetris tetris
WORKDIR tetris
RUN lein cljsbuild once && \
    cp -R tetris.html js /var/www/html

EXPOSE 80
CMD ["/usr/sbin/apache2", "-D", "FOREGROUND"]

